#pragma once
#include<d3d12.h>
#include<dxgi1_6.h>

#pragma comment(lib,"d3d12.lib")
#pragma comment(lib,"dxgi.lib")

namespace DX12
{
	enum class primitive_topology
	{
		TRIANGLE = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE,
		TRIANGLE_LIST = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
		CONTOROL_4_POINT_PATCH_LIST = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST,
		POINT_LIST = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
		PATCH = D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH
	};
}